import {useRouter} from 'next/router'
import Head from 'next/head'
import Sidebar from '../../components/Sidebar'
import Post from '../../components/Post'
import Widgets from '../../components/Widgets'
import CommentModal from '../../components/CommentModal'
import { ArrowLeftIcon } from '@heroicons/react/outline'
import { collection, doc, onSnapshot, orderBy, query } from 'firebase/firestore'
import { db } from '../../firebase'
import { useState, useEffect } from 'react'
import Comment from '../../components/Comment'

export default function PostPage({newsResults, randomUsersResults}) {
    const router = useRouter()
    const { id } = router.query
    const [post, setPost] = useState()
    const [comments, setComments] = useState([])

    // get post data //

    useEffect(
        () => onSnapshot(doc(db, "posts", id), (snapshot) => setPost(snapshot)),
        [db, id]
    )

    // get comments of post //

    useEffect(() => {
            onSnapshot(
                query(
                    collection(db, 'posts', id, 'comments'),
                    orderBy('timestamp', "desc")
                ), (snapshot) => setComments(snapshot.docs)
            )
        },[db, id])

    return (
        <div className=''>
        <Head>
            <title>Post Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='flex min-h-screen mx-auto'>

            {/* SideBar */}

            <Sidebar />

            {/* Post */}

            <div className='xl:ml-[370px] border-l border-r border-gray-200 xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl'>
                <div className='flex items-center space-x-2 py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200'>
                    <div className='hoverEffect'>
                        <ArrowLeftIcon onClick={() => router.push('/')} className='h-5' />
                    </div>
                    <h2 className='text-lg sm:text-xl font-bold cursor-pointer'>Tweet</h2>
                </div>
                <Post id={id} post={post} />
                
                {comments.length > 0 && (
                    <div>
                        {comments.map((comment) => (
                            <Comment key={comment.id} commentId={comment.id} originalPostId={id} comment={comment.data()} />
                        ))}
                    </div>
                )}
            </div>


            {/* Widgets */}

            <Widgets newsResults={newsResults.articles} randomUsersResults={randomUsersResults.results} />

            {/* Modal */}

            <CommentModal />
    

        </main> 
        </div>
    )
}

export async function getServerSideProps() {
    const newsResults = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/entertainment/us.json'
    ).then((res)=>res.json())
  
    const randomUsersResults = await fetch('https://randomuser.me/api/?results=30&inc=name,login,picture'
    ).then((res)=>res.json())
  
    return {
      props:{
        newsResults,
        randomUsersResults,
      }
    }
  }
