import Head from 'next/head'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div className='hidden sm:flex flex-col p-2 xl:items-start fixed h-full'>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen max-w-7xl mx-auto'>
        {/* SideBar */}

        <Sidebar />

        {/* Feed */}



        {/* Widgets */}



        {/* Modal */}


 

      </main> 
    </div>
  )
}
